import path from "node:path";
import {
  ensureDir,
  fs,
  pathExists,
  readJson,
  writeJson,
  writeTextIfMissing,
} from "../utils/fs.js";
import { localSandboxDir } from "./paths.js";
import type { SandboxConfig } from "../types.js";

/**
 * The sandbox recipe model. A recipe turns the per-project `sandbox` config into
 * (1) artifacts materialized under `.worm/sandbox/` and (2) per-slot Claude Code
 * hook wiring written to each slot's `.claude/settings.local.json`. The default
 * `none` recipe is a no-op, so adopters opt in explicitly. The `docker` recipe
 * generalizes the hand-authored sandbox.Dockerfile / sandbox-compose.yml /
 * redirect-to-sandbox.js pattern: no hardcoded home paths — the worktree to
 * mount is supplied at run time via $SANDBOX_DIR (set per slot by the wiring).
 */
export interface SandboxArtifact {
  /** Path relative to `.worm/sandbox/`. */
  relPath: string;
  content: string;
  executable?: boolean;
}

export interface SandboxRecipe {
  readonly name: string;
  artifacts(projectName: string, cfg: SandboxConfig): SandboxArtifact[];
}

/** Minimal slot shape the wiring needs (UniverseSlot satisfies it). */
export interface WiringSlot {
  name: string;
  path: string;
}

const noneRecipe: SandboxRecipe = {
  name: "none",
  artifacts: () => [],
};

const dockerRecipe: SandboxRecipe = {
  name: "docker",
  artifacts(projectName, cfg) {
    return [
      { relPath: "Dockerfile", content: renderDockerfile(cfg) },
      { relPath: "compose.yml", content: renderCompose(projectName, cfg) },
      { relPath: "redirect-to-sandbox.js", content: INTERCEPTOR_SCRIPT, executable: true },
      {
        relPath: "sandbox-policy.json",
        content: JSON.stringify(
          { neverSandbox: cfg.neverSandbox, exemptDirs: cfg.exemptDirs },
          null,
          2
        ) + "\n",
      },
    ];
  },
};

const RECIPES: Record<string, SandboxRecipe> = {
  none: noneRecipe,
  docker: dockerRecipe,
};

export function getRecipe(name: string): SandboxRecipe {
  return RECIPES[name] ?? noneRecipe;
}

function renderDockerfile(cfg: SandboxConfig): string {
  const lines = [
    `# Sandbox image generated by worm. Edit freely — it won't be regenerated.`,
    `FROM ${cfg.image}`,
    "",
  ];
  if (cfg.tools.length > 0) {
    lines.push(
      `RUN apt-get update && apt-get install -y --no-install-recommends ${cfg.tools.join(" ")} \\`,
      `    && rm -rf /var/lib/apt/lists/*`,
      ""
    );
  }
  lines.push(`CMD ["sleep", "infinity"]`, "");
  return lines.join("\n");
}

function renderCompose(projectName: string, cfg: SandboxConfig): string {
  void cfg;
  // `\${VAR}` emits a literal `${VAR}` for compose to interpolate at run time.
  return `# Long-running sandbox container generated by worm.
# Start a slot's sandbox:  SANDBOX_DIR=<slot path> docker compose -p ${projectName}-<N> -f .worm/sandbox/compose.yml up -d
# $SANDBOX_DIR is the worktree to mount (set per slot by worm's session wiring).
# $SANDBOX_CONTAINER overrides the container name (defaults to ${projectName}-sandbox).
name: ${projectName}-sandbox

services:
  sandbox:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${projectName}-sandbox:latest
    container_name: \${SANDBOX_CONTAINER:-${projectName}-sandbox}
    restart: unless-stopped
    working_dir: \${SANDBOX_DIR:?set SANDBOX_DIR to the slot worktree path}
    volumes:
      - \${SANDBOX_DIR}:\${SANDBOX_DIR}
    command: ["sleep", "infinity"]
`;
}

/**
 * Materialize the recipe's artifacts under `sandboxDir`. Idempotent and
 * non-clobbering (writeTextIfMissing) — once generated, the files are the
 * user's to edit, mirroring how `setup.sh` is owned after seeding. Returns the
 * relative paths actually written. A `none` recipe writes nothing.
 */
export async function materializeSandbox(
  sandboxDir: string,
  projectName: string,
  cfg: SandboxConfig
): Promise<string[]> {
  const recipe = getRecipe(cfg.recipe);
  const artifacts = recipe.artifacts(projectName, cfg);
  if (artifacts.length === 0) return [];
  await ensureDir(sandboxDir);
  const written: string[] = [];
  for (const artifact of artifacts) {
    const filePath = path.join(sandboxDir, artifact.relPath);
    if (await writeTextIfMissing(filePath, artifact.content)) {
      if (artifact.executable) await fs.chmod(filePath, 0o755);
      written.push(artifact.relPath);
    }
  }
  return written;
}

// --- per-slot Claude Code hook wiring (.claude/settings.local.json) ---

const HOOK_EVENTS = ["PreToolUse", "SessionStart", "SessionEnd"] as const;

function containerName(projectName: string, slot: WiringSlot): string {
  return `${projectName}-${slot.name}-sandbox`;
}

function slotHookBlock(
  slot0Root: string,
  projectName: string,
  slot: WiringSlot,
  cfg: SandboxConfig
): Record<string, unknown[]> {
  const sandboxDir = localSandboxDir(slot0Root);
  const compose = path.join(sandboxDir, "compose.yml");
  const script = path.join(sandboxDir, "redirect-to-sandbox.js");
  const container = containerName(projectName, slot);
  const project = `${projectName}-${slot.name}`;
  const block: Record<string, unknown[]> = {
    PreToolUse: [
      {
        matcher: "Bash",
        hooks: [{ type: "command", command: `node "${script}" "${container}" "${compose}"` }],
      },
    ],
  };
  if (cfg.autostart) {
    block.SessionStart = [
      {
        hooks: [
          {
            type: "command",
            command: `SANDBOX_DIR="${slot.path}" SANDBOX_CONTAINER="${container}" docker compose -p "${project}" -f "${compose}" up -d`,
          },
        ],
      },
    ];
  }
  if (cfg.autostop) {
    block.SessionEnd = [
      {
        hooks: [
          { type: "command", command: `docker compose -p "${project}" -f "${compose}" down` },
        ],
      },
    ];
  }
  return block;
}

function isWormManaged(entry: unknown, marker: string): boolean {
  const hooks = (entry as { hooks?: unknown })?.hooks;
  return (
    Array.isArray(hooks) &&
    hooks.some((h) => typeof (h as { command?: unknown })?.command === "string" &&
      ((h as { command: string }).command).includes(marker))
  );
}

/**
 * Merge `install` into a slot's `.claude/settings.local.json` (gitignored by
 * convention, so worm never dirties a tracked repo). worm owns only the hook
 * entries it recognises (their commands reference `.worm/sandbox/`): on each run
 * it strips its previous entries and re-adds `install`, leaving every other hook
 * and key intact. Pass an empty `install` to strip. Idempotent. Returns whether
 * the file changed.
 */
async function writeSlotHooks(
  slot0Root: string,
  slotPath: string,
  install: Record<string, unknown[]>
): Promise<boolean> {
  const settingsPath = path.join(slotPath, ".claude", "settings.local.json");
  const marker = localSandboxDir(slot0Root);
  const existed = await pathExists(settingsPath);
  let settings: Record<string, any> = {};
  if (existed) {
    try {
      settings = await readJson<Record<string, any>>(settingsPath);
    } catch {
      settings = {};
    }
  }
  const before = JSON.stringify(settings);

  const hooksRoot: Record<string, any[]> =
    settings.hooks && typeof settings.hooks === "object" && !Array.isArray(settings.hooks)
      ? settings.hooks
      : {};
  for (const event of HOOK_EVENTS) {
    const prev = Array.isArray(hooksRoot[event]) ? hooksRoot[event] : [];
    const keep = prev.filter((entry) => !isWormManaged(entry, marker));
    const next = keep.concat((install[event] as unknown[]) ?? []);
    if (next.length > 0) hooksRoot[event] = next;
    else delete hooksRoot[event];
  }
  if (Object.keys(hooksRoot).length > 0) settings.hooks = hooksRoot;
  else delete settings.hooks;

  if (JSON.stringify(settings) === before) return false;
  // Don't create an empty settings.local.json just to write `{}`.
  if (!existed && Object.keys(settings).length === 0) return false;
  await ensureDir(path.dirname(settingsPath));
  await writeJson(settingsPath, settings);
  return true;
}

/** Install (or, for recipe `none`, strip) worm's sandbox hooks for one slot. */
export async function applySlotWiring(
  slot0Root: string,
  projectName: string,
  slot: WiringSlot,
  cfg: SandboxConfig
): Promise<boolean> {
  const install =
    cfg.recipe === "none" ? {} : slotHookBlock(slot0Root, projectName, slot, cfg);
  return writeSlotHooks(slot0Root, slot.path, install);
}

/** Remove worm's sandbox hooks from a slot (used on `destroy`). */
export async function stripSlotWiring(slot0Root: string, slotPath: string): Promise<boolean> {
  return writeSlotHooks(slot0Root, slotPath, {});
}

// The interceptor is embedded via String.raw so its regex backslashes survive
// (a normal template literal would mangle `\s`, `\d`, …). It contains no
// backticks and no `${...}`, so String.raw reproduces it verbatim. Policy
// (neverSandbox / exemptDirs) is read at run time from the sibling
// sandbox-policy.json, so the script itself is config-independent.
const INTERCEPTOR_SCRIPT = String.raw`#!/usr/bin/env node
// PreToolUse(Bash) hook generated by worm. Denies filesystem-mutating commands
// and ad-hoc script runs on the host, redirecting them into a long-running
// docker sandbox whose blast radius is limited to the mounted worktree.
//
// Usage (from settings.local.json):  node redirect-to-sandbox.js <container> <composePath>
// Policy is read from the sibling sandbox-policy.json. Append ' #bypass-hook'
// to any command to run it on the host anyway.
const fs = require('fs');
const path = require('path');

const containerName = process.argv[2] || 'sandbox';
const composePath = process.argv[3] || '';
const projectDir = process.env.CLAUDE_PROJECT_DIR || process.cwd();

let policy = { neverSandbox: ['node', 'npm', 'npx', 'pnpm', 'yarn'], exemptDirs: [] };
try {
  policy = JSON.parse(fs.readFileSync(path.join(__dirname, 'sandbox-policy.json'), 'utf8'));
} catch (e) { /* fall back to defaults */ }

const FILE_OPS = new Set(['rm', 'rmdir', 'mv', 'cp', 'mkdir', 'touch', 'ln', 'chmod', 'chown', 'truncate', 'shred', 'install']);
const INTERPRETERS = new Set(['bash', 'sh', 'zsh', 'python', 'python3', 'perl', 'ruby', 'php']);
const NODE_TOOLS = new Set(policy.neverSandbox || []);

const SCRIPT_TOKEN = /(?:^|[\s='"(])((?:\.{1,2}\/|\/)?[^\s'"()]*\.(?:sh|bash|zsh|py|rb|pl|php)|\.{1,2}\/[^\s'"()]+)(?=$|[\s'")])/;
const READONLY_CHECK = /\bphp\s+-l\b/;

const exemptNames = ['worm', 'claude'].concat(policy.exemptDirs || []);
const EXCLUDED_DIR = new RegExp('(?:^|[\\s=\'"~])\\.?~?/?[^\\s\'"]*/\\.(?:' + exemptNames.join('|') + ')/');

function allow() { process.exit(0); }

function deny() {
  const startHint = composePath
    ? '\n\nIf the container is not running, start it:\n  docker compose -f ' + composePath + ' up -d'
    : '';
  const reason =
    'This command mutates the filesystem or runs an ad-hoc script on the host. ' +
    'Run it inside the \'' + containerName + '\' docker sandbox instead, so its blast radius is ' +
    'limited to the mounted worktree. Re-run it as (wrap your command in single quotes):\n' +
    '  docker exec ' + containerName + ' bash -lc \'<your original command>\'\n\n' +
    'The sandbox mounts ' + projectDir + ' read-write at the same absolute path.' +
    startHint +
    '\n\nAppend \' #bypass-hook\' to run on the host anyway.';
  process.stdout.write(JSON.stringify({
    hookSpecificOutput: {
      hookEventName: 'PreToolUse',
      permissionDecision: 'deny',
      permissionDecisionReason: reason,
    },
  }));
  process.exit(0);
}

function baseName(token) { const parts = token.split('/'); return parts[parts.length - 1]; }

function shouldRedirect(command) {
  if (/#bypass-hook\s*$/.test(command)) return false;
  if (/^\s*(?:sudo\s+)?docker(?:\s|-compose\b|$)/.test(command)) return false;
  if (EXCLUDED_DIR.test(command)) return false;
  const segments = command.split(/\n|;|&&|\|\|/);
  for (let segment of segments) {
    segment = segment.trim();
    if (!segment) continue;
    segment = segment.replace(/^(?:\w+=(?:'[^']*'|"[^"]*"|\S+)\s+)*/, '').replace(/^sudo\s+/, '');
    const firstToken = segment.split(/\s+/)[0] || '';
    if (!firstToken) continue;
    const program = baseName(firstToken);
    if (NODE_TOOLS.has(program)) continue;
    if (INTERPRETERS.has(program) && READONLY_CHECK.test(segment)) continue;
    if (FILE_OPS.has(program)) return true;
    if (/^(?:\.{1,2}\/|\/)?[^\s]*\.(?:sh|bash|zsh|py|rb|pl|php)$/.test(firstToken)) return true;
    if (INTERPRETERS.has(program) && SCRIPT_TOKEN.test(segment)) return true;
  }
  return false;
}

let input = '';
process.stdin.on('data', (chunk) => { input += chunk; });
process.stdin.on('end', () => {
  let command = '';
  try { command = (JSON.parse(input).tool_input || {}).command || ''; } catch (e) { allow(); }
  if (!command) allow();
  if (shouldRedirect(command)) deny();
  allow();
});
`;
