import path from "node:path";
import { ensureDir, fs, writeTextIfMissing } from "../utils/fs.js";
import type { SandboxConfig } from "../types.js";

/**
 * The sandbox recipe model. A recipe turns the per-project `sandbox` config into
 * concrete artifacts materialized under `.worm/sandbox/`. The default `none`
 * recipe is a no-op, so adopters opt in explicitly. The `docker` recipe is a
 * generalization of the hand-authored sandbox.Dockerfile / sandbox-compose.yml
 * pattern: no hardcoded home paths — the worktree to mount is supplied at run
 * time via $SANDBOX_DIR (set per slot by the generated session wiring, 7b).
 */
export interface SandboxArtifact {
  /** Path relative to `.worm/sandbox/`. */
  relPath: string;
  content: string;
  executable?: boolean;
}

export interface SandboxRecipe {
  readonly name: string;
  artifacts(projectName: string, cfg: SandboxConfig): SandboxArtifact[];
}

const noneRecipe: SandboxRecipe = {
  name: "none",
  artifacts: () => [],
};

const dockerRecipe: SandboxRecipe = {
  name: "docker",
  artifacts(projectName, cfg) {
    return [
      { relPath: "Dockerfile", content: renderDockerfile(cfg) },
      { relPath: "compose.yml", content: renderCompose(projectName, cfg) },
    ];
  },
};

const RECIPES: Record<string, SandboxRecipe> = {
  none: noneRecipe,
  docker: dockerRecipe,
};

export function getRecipe(name: string): SandboxRecipe {
  return RECIPES[name] ?? noneRecipe;
}

function renderDockerfile(cfg: SandboxConfig): string {
  const lines = [
    `# Sandbox image generated by worm. Edit freely — it won't be regenerated.`,
    `FROM ${cfg.image}`,
    "",
  ];
  if (cfg.tools.length > 0) {
    const pkgs = cfg.tools.join(" ");
    lines.push(
      `RUN apt-get update && apt-get install -y --no-install-recommends ${pkgs} \\`,
      `    && rm -rf /var/lib/apt/lists/*`,
      ""
    );
  }
  // Stay alive so `docker exec` can run commands against it on demand.
  lines.push(`CMD ["sleep", "infinity"]`, "");
  return lines.join("\n");
}

function renderCompose(projectName: string, cfg: SandboxConfig): string {
  // `\${VAR}` emits a literal `${VAR}` for compose to interpolate at run time.
  // The worktree is mounted read-write at the SAME absolute path so the agent's
  // absolute-path commands work unchanged inside the container.
  void cfg;
  return `# Long-running sandbox container generated by worm.
# Start a slot's sandbox:  SANDBOX_DIR=<slot path> docker compose -p ${projectName}-<N> -f .worm/sandbox/compose.yml up -d
# $SANDBOX_DIR is the worktree to mount (set per slot by worm's session wiring).
# $SANDBOX_CONTAINER overrides the container name (defaults to ${projectName}-sandbox).
name: ${projectName}-sandbox

services:
  sandbox:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${projectName}-sandbox:latest
    container_name: \${SANDBOX_CONTAINER:-${projectName}-sandbox}
    restart: unless-stopped
    working_dir: \${SANDBOX_DIR:?set SANDBOX_DIR to the slot worktree path}
    volumes:
      - \${SANDBOX_DIR}:\${SANDBOX_DIR}
    command: ["sleep", "infinity"]
`;
}

/**
 * Materialize the recipe's artifacts under `sandboxDir`. Idempotent and
 * non-clobbering (writeTextIfMissing) — once generated, the files are the
 * user's to edit, mirroring how `setup.sh` is owned after seeding. Returns the
 * relative paths actually written. A `none` recipe writes nothing.
 */
export async function materializeSandbox(
  sandboxDir: string,
  projectName: string,
  cfg: SandboxConfig
): Promise<string[]> {
  const recipe = getRecipe(cfg.recipe);
  const artifacts = recipe.artifacts(projectName, cfg);
  if (artifacts.length === 0) return [];
  await ensureDir(sandboxDir);
  const written: string[] = [];
  for (const artifact of artifacts) {
    const filePath = path.join(sandboxDir, artifact.relPath);
    if (await writeTextIfMissing(filePath, artifact.content)) {
      if (artifact.executable) await fs.chmod(filePath, 0o755);
      written.push(artifact.relPath);
    }
  }
  return written;
}
